### PR TITLE
upgrade to FFmpeg 4.2

### PR DESCRIPTION
**Pull request by retokromer**
On my end it works fine, however see: https://github.com/Homebrew/homebrew-core/pull/42827.

### CODE REVIEW

**Comment by robertleeblairjr** [comment]
> On my end it works fine, however see: [Homebrew/homebrew-core#42827](https://github.com/Homebrew/homebrew-core/pull/42827).

Is your build testing with mpv, since FFmpeg is a requirement? From the Travis check, it was failing for mpv which has python bindings, as well. Are you using the python bindings with mpv?

**Comment by retokromer** [comment]
@robertleeblairjr Not sure I understand you carefully. To me `mpv` is not a requirement of `ffmpeg`. I know next to nothing about Travis. Yet I just tried again and, on my end, I can install FFmpeg 4.2 via our formula with options:

Screenshot 2019-08-07 at 07 48 33

**Comment by robertleeblairjr** [comment]
> @robertleeblairjr Not sure I understand you carefully. To me `mpv` is not a requirement of `ffmpeg`. I know next to nothing about Travis. Yet I just tried again and, on my end, I can install FFmpeg 4.2 via our formula with options:
> 
> Screenshot 2019-08-07 at 07 48 33

I wasn't inferring mpv was a requirement of FFmpeg. However, FFmpeg is a requirement of mpv. Since it's a dependency of mpv, then the link test probably rebuilds those formula which FFmpeg is listed as a requirement. I believe one of the other build requirements of mpv is python. That was my only inferrance to mpv failing in the submission. Perhaps, it was building in your environment but wasn't in Travis because of requiring more extensive build/configuration/dependency platform. But, most likely you're not rebuilding mpv with the new FFmpeg but just this formula only.

> mpv: stable 0.29.1 (bottled), HEAD
Media player based on MPlayer and mplayer2
https://mpv.io
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb
==> Dependencies
Build: docutils ✔, pkg-config ✔, python ✔
Required: ffmpeg ✔, jpeg ✔, libarchive ✔, libass ✔, little-cms2 ✔, lua@5.1 ✔, mujs ✔, uchardet ✔, vapoursynth ✔, youtube-dl ✔
==> Options
--HEAD
	Install HEAD version

**Comment by retokromer** [comment]
>But, most likely you're not rebuilding mpv with the new FFmpeg but just this formula only.

Indeed. The problem is actually `mpv`, which needs to be modified, not `ffmpeg`.

**Comment by robertleeblairjr** [comment]
> > But, most likely you're not rebuilding mpv with the new FFmpeg but just this formula only.
> 
> Indeed. The problem is actually `mpv`, which needs to be modified, not `ffmpeg`.

Yep. That's why I suggested in another PR for Homebrew-Core that the OP submit a bug report to mpv.

Have you tried to build mpv, as well, to see if it was just failing on Travis and not on other devices?

Copy/paste from mpv compile page on GH.

> FFmpeg vs. Libav
Generally, mpv should work with the latest release as well as the git version of FFmpeg. Libav support is currently broken, because they did not add certain FFmpeg API changes which mpv relies on.
FFmpeg ABI compatibility
mpv does not support linking against FFmpeg versions it was not built with, even if the linked version is supposedly ABI-compatible with the version it was compiled against. Expect malfunctions, crashes, and security issues if you do it anyway.
The reason for not supporting this is because it creates far too much complexity with little to no benefit, coupled with absurd and unusable FFmpeg API artifacts.
Newer mpv versions will refuse to start if runtime and compile time FFmpeg library versions mismatch.

**Comment by retokromer** [comment]
>Yep. That's why I suggested in another PR for Homebrew-Core that the OP submit a bug report to mpv.

[I tried but got only the response that it’s not their fault.](https://github.com/mpv-player/mpv/issues/6850)

**Comment by robertleeblairjr** [comment]
> > Yep. That's why I suggested in another PR for Homebrew-Core that the OP submit a bug report to mpv.
> 
> [I tried but got only the response that it’s not their fault.](https://github.com/mpv-player/mpv/issues/6850)

I just read that on their compile page they don't support linking against FFmpeg versions that their current branch is not built against. So, whichever version FFmpeg 4.1.x that the project is currently using is the only supported version. Seems to cause some conflicts with the Homebrew-Core formula and they may need to determine if keeping each formula is necessary. Of course, it could be resolved soon by mpv whenever they update their project build with FFmpeg 4.2.

**Comment by retokromer** [comment]
>I just read that on their compile page they don't support linking against FFmpeg versions that their current branch is not built against. So, whichever version FFmpeg 4.1.x that the project is currently using is the only supported version. Seems to cause some conflicts with the Homebrew-Core formula and they may need to determine if keeping each formula is necessary. Of course, it could be resolved soon by mpv whenever they update their project build with FFmpeg 4.2.

It’s frustrating that they are allowed to block the deployment of FFmpeg 4.2 via Homebrew.

**Comment by robertleeblairjr** [comment]
> > I just read that on their compile page they don't support linking against FFmpeg versions that their current branch is not built against. So, whichever version FFmpeg 4.1.x that the project is currently using is the only supported version. Seems to cause some conflicts with the Homebrew-Core formula and they may need to determine if keeping each formula is necessary. Of course, it could be resolved soon by mpv whenever they update their project build with FFmpeg 4.2.
> 
> It’s frustrating that they are allowed to block the deployment of FFmpeg 4.2 via Homebrew.

Yes. I would believe that when it comes to dependencies, which should have precedence for compatibility, over the formula which are dependent on them. mpv requires ffmpeg but not vice versa and since there are other formula which rely on FFmpeg, then a need to change mpv for compatibility should be met. Another person, made a recommendation that the formula could possibly be rebuilt via a revision whenever FFmpeg PR is made but I don't if it's doable for this project. Definitely, devs would know the answer to this and I would hope could take a quick look for an easy solution. I'm sure this can't be the first time something of this nature has happened with linking problems.

**Comment by retokromer** [comment]
I suggest to wait here until the revision bump of `mpv` has been made. In despair, this formula updated to 4.2 (as well as the official one updated to 4.2) seems to work fine, if `mpv` is replaced by its cask (which includes ffmpeg 4.0.2):
```
brew uninstall mpv
brew cask install mpv
```

**Comment by slhck** [comment]
I kind of lost track in all the conversations, but am I correct that we're waiting for an `mpv` formula revision, or at least for https://github.com/Homebrew/homebrew-core/pull/42827 to be resolved before we can merge this PR?

**Comment by retokromer** [comment]
@slhck If we ignore `mpv` (respectively suggest to use the cask), then we can merge, but I would personally prefer to have https://github.com/Homebrew/homebrew-core/pull/42827#issuecomment-521474699 resolved previously.

**Pull request closed without merging**
