### PR TITLE
Tesseract lang info msg

### PR DESCRIPTION
**Pull request by varenc**
This is a so-so compromise for the discussion in #11

Not 100% sure on this and looking for feedback. Thoughts?

### CODE REVIEW

**Review by retokromer — COMMENTED** [review]
I would suggest to not include `ohai "============="` lines, but to use `opoo` instead of `ohai` for the warning line.

**Comment by slhck** [comment]
I'll have a look whether it's possible to add the caveat dynamically. This change really looks like a workaround. Doesn't Homebrew have variables available at the time. If printing the caveat? 

Using `opoo` has the semantics of "hey, you did something wrong", which is actually not the case. I'd like to avoid that.

Or what about adding the message in the tesseract formula itself, upstream? Has that been discussed?

**Comment by retokromer** [comment]
>Or what about adding the message in the tesseract formula itself, upstream? Has that been discussed?

This is already done: https://github.com/Homebrew/homebrew-core/blob/fcbc6496d3acdbf330657621b9011dcd9c2c5b3b/Formula/tesseract.rb#L67

**Comment by retokromer** [comment]
I would suggest to refrain from adding an additional caveat/message, and either to add the additional option or to leave as it is.

**Comment by retokromer** [comment]
>Using `opoo` has the semantics of "hey, you did something wrong", which is actually not the case. I'd like to avoid that.

I am not sure this is correct. In fact a simple `brew options ffmpeg` gives an `opoo` warning:
```
Warning: ffmpeg is provided by core, but is now shadowed by varenc/ffmpeg/ffmpeg.
```
and – to me – it does not imply that something is wrong.

That said, to me an additional warning is pleonastic.

**Comment by slhck** [comment]
> I am not sure this is correct. In fact a simple `brew options ffmpeg` gives an `opoo` warning:

You're right, I didn't know that, sorry.

> That said, to me an additional warning is pleonastic.

I agree.

**Comment by retokromer** [comment]
Any news on this?

**Comment by slhck** [comment]
I squashed the commits into one, slightly shortened the message, used `opoo`, and used the default for multiline strings in Homebrew. LGTM now for merging into master.

**Review by retokromer — APPROVED** [review]

**Pull request merged**
